/* THROWAWAY gameplay prototype. All state is in memory. */
(function(root){
'use strict';
var types=['代码','对话','规划'], presets=[
{name:'直接生成',get:false,check:false,read:false,write:false,loops:0},
{name:'查证处理',get:true,check:true,read:false,write:false,loops:2},
{name:'查证并记忆',get:true,check:true,read:false,write:true,loops:2},
{name:'记忆处理',get:false,check:true,read:true,write:false,loops:2},
{name:'记忆＋获取后备',get:true,check:true,read:true,write:false,loops:2}];
function size(p){return 3+(p.get?2:0)+(p.check?2:0)+(p.read?1:0)+(p.write?1:0);}
function shape(n,w){w=w||2;var a=[];for(var i=0;i<n;i++)a.push([i%w,Math.floor(i/w)]);return a;}
function rotate(a){var b=a.map(function(p){return[-p[1],p[0]];}),mx=Math.min.apply(null,b.map(p=>p[0])),my=Math.min.apply(null,b.map(p=>p[1]));return b.map(p=>[p[0]-mx,p[1]-my]);}
class Game{
 constructor(mode,opt){opt=opt||{};this.mode=mode||'flow';this.cols=this.mode==='demo'?4:6;this.rows=this.mode==='demo'?3:4;this.duration=this.mode==='demo'?25:90;this.time=0;this.tasks=[];this.log=[];this.plans=presets.map(p=>({...p}));this.mem=[];this.skills=[2,1,1];this.samples=[0,0,0];this.rep=[0,0,0];this.money=0;this.good=0;this.bad=0;this.seq=0;this.spawnSeq=0;this.next=7;this.xp=opt.xp!==false;this.bias=opt.bias!==false;this.ended=false;this.experience=Array.from({length:this.rows},()=>Array.from({length:this.cols},()=>({type:-1,n:0})));if(this.mode==='demo'){this.add({name:'A',type:0,total:10,deadline:20,token:100,cells:shape(4)});this.add({name:'B',type:1,total:10,deadline:12,token:100,cells:shape(3,3)});}else{this.spawn();this.spawn();}}
 note(s){this.log.unshift(this.time.toFixed(1)+'s · '+s);this.log=this.log.slice(0,30);}
 add(o){var t={id:++this.seq,name:o.name||'用户'+this.seq,type:o.type||0,level:o.level||0,text:o.text||'请完成请求',version:o.version||1,arrival:this.time,deadline:this.time+(o.deadline||20),token:o.token||100,state:'queued',total:o.total||10,plan:{...this.plans[0]},cells:o.cells||shape(3),x:null,y:null,started:false,paused:false,p:0,work:0,bill:0,cost:0,loops:0,support:0,trace:[],stage:null};this.tasks.push(t);this.note(t.name+'提出'+types[t.type]+'请求');return t;}
 spawn(){var i=this.spawnSeq++,type=[0,2,1,0,1,2][i%6],level=[1,2,3,2,1,3][i%6],dead=[18,23,24,19,14,24][i%6];if(this.bias&&i>5){var w=this.rep.map(r=>Math.max(1,4+r)),s=w.reduce((a,b)=>a+b,0),v=(i*13)%s;for(var k=0;k<3;k++){if(v<w[k]){type=k;break;}v-=w[k];}}var texts=[['输出简单脚本','核实接口资料后修复脚本','结合资料修复复杂逻辑'],['写一段欢迎语','根据背景写角色对白','核实背景，保持长对话一致'],['给出简单安排','查询场地，安排预算内的活动','核实新条件后调整完整计划']];var ver=i>=8&&i%3===0?2:1;var t=this.add({name:['开发者','创作者','社团用户'][type]+' '+(i+1),type:type,level:level,deadline:dead,text:texts[type][Math.min(2,level-1)],version:ver,total:8+level*2});if(this.mode==='basic')t.cells=shape([3,5,6,4,3,7][i%6]);return t;}
 choose(t,p){if(t.started||t.state!=='queued'||this.mode!=='flow')return false;t.plan={...p};t.cells=shape(size(p),p.width||2);return true;}
 legal(t,cells,x,y){return cells.every(([dx,dy])=>x+dx>=0&&y+dy>=0&&x+dx<this.cols&&y+dy<this.rows&&!this.tasks.some(o=>o.id!==t.id&&o.state==='running'&&o.cells.some(([a,b])=>o.x+a===x+dx&&o.y+b===y+dy)));}
 place(t,cells,x,y){if(!['queued','withdrawn','running'].includes(t.state)||!this.legal(t,cells,x,y))return false;t.cells=cells.map(p=>p.slice());t.x=x;t.y=y;t.state='running';if(!t.started){t.started=true;t.base=this.skills[t.type];t.key=[t.type,t.level,t.version].join(':');t.memory=this.mem.find(m=>m.key===t.key&&m.until>this.time)||null;t.stage=this.mode!=='flow'?'base':t.plan.read?'read':t.plan.get?'get':'generate';t.trace.push('锁定模型等级'+t.base+'、方案'+t.plan.name);}return true;}
 withdraw(t){if(!t||t.state!=='running')return false;t.state='withdrawn';t.x=t.y=null;this.note(t.name+'撤回，进度保留');return true;}
 togglePause(t){if(!t||t.state!=='running')return false;t.paused=!t.paused;this.note(t.name+(t.paused?'暂停计算，仍占空间且期限继续':'继续计算'));return true;}
 seconds(t){return({base:t.total,read:1,get:4,generate:3,check:2,repair:2,write:1})[t.stage]||1;}
 area(t){return({base:t.cells.length,read:1,get:2,generate:3,check:2,repair:3,write:1})[t.stage]||0;}
 capacity(t){return Math.min(t.base+2,t.base+t.support);}
 boost(t){if(!this.xp||this.mode!=='flow')return 1;return 1+.08*t.cells.reduce((n,[x,y])=>{var e=this.experience[t.y+y][t.x+x];return n+(e.type===t.type?e.n:0);},0)/t.cells.length;}
 finish(t,ok,why,at){if(['done','failed','closed'].includes(t.state))return;t.ok=ok;t.state=ok?'done':'failed';t.reason=why;t.finished=at;t.x=t.y=null;t.income=Math.floor(t.bill)*(this.mode==='demo'?1:.1);t.net=t.income-t.cost;this.money+=t.net;this.rep[t.type]+=ok?1:-2;if(ok){this.good++;this.samples[t.type]++;}else this.bad++;this.note(t.name+(ok?'达标':'失败')+'：'+why+'，净收'+t.net.toFixed(1));}
 after(t,at){var s=t.stage;t.trace.push(at.toFixed(1)+'s 完成'+s);t.p=0;if(s==='base'){this.finish(t,true,'计算完成',at);return;}if(s==='read'){if(t.memory){t.support=1;t.trace.push('记忆命中');t.stage='generate';}else if(t.plan.get){t.trace.push('未命中，获取后备');t.stage='get';}else this.finish(t,false,'记忆未命中且无后备',at);return;}if(s==='get'){t.support=Math.max(1,t.support);t.stage='generate';return;}if(s==='generate'||s==='repair'){if(s==='repair')t.support++;if(t.plan.check)t.stage='check';else this.finish(t,this.capacity(t)>=t.level,'直接交付',at);return;}if(s==='check'){if(this.capacity(t)>=t.level){if(t.plan.write)t.stage='write';else this.finish(t,true,'检查通过',at);}else if(t.loops<t.plan.loops&&t.level<=t.base+2){t.loops++;t.trace.push('能力不足，第'+t.loops+'次修正');t.stage='repair';}else this.finish(t,false,'检查未通过／返工上限',at);return;}if(s==='write'){this.mem=this.mem.filter(m=>m.key!==t.key);this.mem.push({key:t.key,type:t.type,level:t.level,version:t.version,until:at+65});if(this.mem.length>6)this.mem.shift();this.finish(t,true,'通过并写入记忆',at);}}
 run(t,dt,at){var used=0;while(used<dt-1e-9&&t.state==='running'){var speed=this.boost(t),d=Math.min(dt-used,(this.seconds(t)-t.p)/speed),s=t.stage,x=t.x,y=t.y;t.p+=d*speed;t.work+=d*speed;if(this.mode==='flow')t.cost+=d*this.area(t)*.1;if(s==='base'||s==='generate')t.bill=Math.max(t.bill,Math.min(t.token,t.token*t.p/this.seconds(t)));used+=d;if(t.p>=this.seconds(t)-1e-9){var good=this.good;this.after(t,at+used);if(this.good>good&&this.xp&&this.mode==='flow')for(var c of t.cells){var e=this.experience[y+c[1]][x+c[0]];e.n=e.type===t.type?Math.min(2,e.n+1):1;e.type=t.type;}}}}
 advance(dt){if(this.ended)return;var target=Math.min(this.duration,this.time+dt);while(this.time<target-1e-9){var end=Math.min(target,this.mode==='demo'&&!this.demoC?2:Infinity,this.mode!=='demo'?this.next:Infinity),start=this.time;for(var t of this.tasks){if(!['queued','withdrawn','running'].includes(t.state))continue;if(t.state==='running'&&!t.paused)this.run(t,Math.max(0,Math.min(end-start,t.deadline-start)),start);if(['queued','withdrawn','running'].includes(t.state)&&t.deadline<=end+1e-9)this.finish(t,false,'超时',t.deadline);}this.time=end;if(this.mode==='demo'&&!this.demoC&&end>=2){this.demoC=true;this.add({name:'C',type:2,total:5,deadline:7,token:50,cells:shape(6)});}if(this.mode!=='demo'&&end>=this.next-1e-9){if(end<this.duration)this.spawn();this.next+=7;}}if(this.time>=this.duration){for(var t of this.tasks)if(['queued','running','withdrawn'].includes(t.state))this.finish(t,false,'本轮结束',this.time);this.ended=true;}}
 reply(t){if(!t||!['done','failed'].includes(t.state))return;t.state='closed';this.note(t.name+'收到回复');}
 train(k){if(this.samples[k]<3||this.money<8)return false;this.samples[k]-=3;this.money-=8;this.skills[k]++;this.note(types[k]+'能力升至'+this.skills[k]);return true;}
}
var api={Game:Game,plans:presets,size:size,shape:shape,rotate:rotate,types:types};if(typeof module!=='undefined')module.exports=api;else root.Proto=api;
})(typeof window!=='undefined'?window:globalThis);

